# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nasa-will-it-rain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_65e4c7063a0e4328a06b5d92c3a91336 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_728357f27e9a46358a88ebf492d1b16d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_65e4c7063a0e4328a06b5d92c3a91336 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nasa-will-it-rain'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1511d3f3f898444e8b1d37147ad2d103 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_65e4c7063a0e4328a06b5d92c3a91336 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'